### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Haoyanlong** [yufengm/Adaptive#3]
@yufengm 
After one epoch, I want to calculate the METEOR score, but error as follow:
computing METEOR score...
Traceback (most recent call last):
  File "train_model.py", line 268, in <module>
    main(args)   
  File "train_model.py", line 177, in main
    method_score = coco_eval(adaptive, args, epoch)
  File "/home1/haoyanlong/imagecaption/Adaptive_Attention/code/utils.py", line 173, in coco_eval
    cocoEval.evaluate()
  File "/home1/haoyanlong/imagecaption/Adaptive_Attention/code/coco/pycocoevalcap/eval.py", line 51, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "/home1/haoyanlong/imagecaption/Adaptive_Attention/code/coco/pycocoevalcap/meteor/meteor.py", line 38, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/home1/haoyanlong/imagecaption/Adaptive_Attention/code/coco/pycocoevalcap/meteor/meteor.py", line 56, in _stat
    self.meteor_p.stdin.write('{}\n'.format(score_line))
IOError: [Errno 32] Broken pipe

**Comment by yufengm** [comment]
It seems that I forgot to add transforms.Scale( 256 ) or transforms.Resize( 256 ) in 
https://github.com/yufengm/Adaptive/blob/4c0555af546cdbd49e99ff1bd6e91d1654ae0cd2/train.py#L31

Thanks for spotting this.
